version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres_prisma
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_forte
      POSTGRES_DB: meuappdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:



